mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  username: root
  password: root
  log_level: dev
  config: "charset=utf8mb4&parseTime=True&loc=Local"
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  'log_in_console:': false
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2024-10-22"
  bei_an: 鄂ICP备2024058587号
  title: labulat
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/gg.png
  version: 1.0.0
  email: 3058524082.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 老tcoding
  job: 后端开发
  addr: 湖北武汉
  slogan: Think different
  slogan_en: ""
  web: http://www.hbbxht.top/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao
qq:
  app_id: ""
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: true
  access_key: pJBm8P0Bxu06pfGb_vD1vLFt_6ITfciVPscy00zN
  secret_key: vyMt5vXvm_Vyf2vBYIH0pH4jkwNkD_yS1-qa93rt
  bucket: hbbxht
  cdn: https://sly9bn5nh.hn-bkt.clouddn.com/
  zone: z2
  prefix: "gvb"
  size: 5
hua_wei:
  enable: true
  access_key: 7ID4LNWHGNBQYNBUUATW
  secret_key: zx9cV95JlcYdp9axnvAwQ2D1te6w10gSi9OSL6Gl
  bucket: tblog
  end_point: obs.cn-east-3.myhuaweicloud.com
  prefix: "gvb"
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 3058524082@qq.com
  password: XXX
  default_from_email: 老tcoding
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
upload:
  size: 2
  path: uploads/file
