mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  username: root
  password: root
  log_level: dev
  config: ""
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  'log_in_console:': false
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2024-10-22"
  bei_an: 鄂ICP备2024058587号
  title: labulat
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/gg.png
  version: 1.0.0
  email: 3058524082.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 老tcoding
  job: 后端开发
  addr: 湖北武汉
  slogan: Think different
  slogan_en: ""
  web: http://www.hbbxht.top/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao
qq:
  app_id: ""
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: fengfengzhidao
  cdn: xx://xx.xx.com
  zone: XX
  prefix: ""
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 3058524082@qq.com
  password: XXX
  default_from_email: 老tcoding
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
